import { IBM_Plex_Mono } from "next/font/google";
import { Providers } from "./provider";
import { Head } from "next/head";
const inter = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "600", "500", "700"],
  style: ["normal"],
});
import "./globals.css";

export const metadata = {
  title: "Ghostify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
